In this task
First I create an array of even integers from 30 to 70
Second I generate 15 random numbers from standard normal distribution
Third create two matrices for cross product
Fourth complete determinants
Fifth create a 3x3 and 5x5 matrice with random values and find max and min values of the 5x5 matrice
Sixth compute mean, standard deviation and variance. 

In [1]:
#First, let's create an array of even integers from 30 to 70:
import numpy as np

# Create array of even integers from 30 to 70
even_array = np.arange(30, 71, 2)
print("Array of even integers from 30 to 70:")
print(even_array)

# Generate 15 random numbers from standard normal distribution
normal_array = np.random.standard_normal(15)
print("\
Array of 15 random numbers from standard normal distribution:")
print(normal_array)

# Create two matrices for cross product
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Compute cross product
cross_product = np.cross(matrix1, matrix2)
print("\
Cross product of matrices:")
print(cross_product)

# Compute determinant of matrix1
det = np.linalg.det(matrix1)
print("\
Determinant of first matrix:")
print(det)

# Create a 3x3 array with random values
random_3x3 = np.random.rand(3, 3)
print("\
3x3 array with random values:")
print(random_3x3)

# Create a 5x5 array with random values
random_5x5 = np.random.rand(5, 5)

# Find the minimum and maximum values in the 5x5 array
min_value = np.min(random_5x5)
max_value = np.max(random_5x5)
print("\
5x5 array with random values:")
print(random_5x5)
print("\
Minimum value in 5x5 array:", min_value)
print("Maximum value in 5x5 array:", max_value)


# Create a sample array
sample_array = np.random.rand(4, 3)

# Compute mean, standard deviation, and variance along second axis
mean = np.mean(sample_array, axis=1)
std = np.std(sample_array, axis=1)
var = np.var(sample_array, axis=1)

print("\
Sample array:")
print(sample_array)
print("\
Mean along second axis:", mean)
print("Standard deviation along second axis:", std)
print("Variance along second axis:", var)


Array of even integers from 30 to 70:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]
Array of 15 random numbers from standard normal distribution:
[-0.52365658 -0.80939378  0.93076713 -0.17248073 -0.4813883  -0.70782984
  0.91882782  0.35608577  1.00258669 -1.78881969  0.15590042  0.23348807
 -1.23510515 -2.12044913 -0.63932085]
Cross product of matrices:
[-4 -4]
Determinant of first matrix:
-2.0000000000000004
3x3 array with random values:
[[0.17814787 0.51980746 0.4858947 ]
 [0.41419004 0.52135334 0.28362113]
 [0.61877348 0.01270406 0.30561881]]
5x5 array with random values:
[[0.32972207 0.91509587 0.20136175 0.22614459 0.78335104]
 [0.68844822 0.98168253 0.57401977 0.25695817 0.1963962 ]
 [0.63536233 0.18345638 0.62609344 0.67075561 0.82405712]
 [0.81544006 0.83109897 0.06456837 0.89949085 0.67151055]
 [0.02879552 0.65423197 0.44589033 0.19829161 0.78337225]]
Minimum value in 5x5 array: 0.028795519984244677
Maximum value in 5x5 array: 0.9816825341972388
Sample arra

/tmp/ipykernel_21021/1703662325.py:20: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  cross_product = np.cross(matrix1, matrix2)
